

services:
  oracle-xe:
    image: container-registry.oracle.com/database/express
    container_name: oracle
    ports:
      - "1521:1521"

    environment:
      - ORACLE_PWD=Manish123
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
