
services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=Password123
      - ORACLE_SID=XE
      - ORACLE_PDB=XEPDB1
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
