APP_BASE_URL: http://localhost:8081
ESEWA_MERCHANT_CODE: EPAYTEST



server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: elearn
    password: elearn123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
esewa:
  merchant:
    code: EPAYTEST
  urls:
    payment: https://uat.esewa.com.np/epay/main
    verification: https://uat.esewa.com.np/epay/transrec
    success: http://localhost:8081/api/orders/esewa/success
    failure: http://localhost:8081/api/orders/esewa/failure
