server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: elearn
    password: elearn123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
